# Site settings
title: My GitHub Page
email: dustin@protocol96.com
description: > # this means to ignore newlines until "baseurl:"
  My GitHub Page for random posts and testing
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://dustinhennis.github.io" # the base hostname & protocol for your site
twitter_username: dustinhennis
github_username:  dustinhennis

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext
