title: dustinhennis GitHub Pages
author: Dustin Hennis
email: dustin at protocol96 dot com
description: > # this means to ignore newlines until "show_exerpts:"
  My GitHub page for random posts and testing
show_excerpts: true # set to true to show excerpts on the homepage
baseurl: /

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Dustin Hennis
  tagline: DevOps Engineer
  date_format: "%b %-d, %Y"
  style: black
  showNav: true
  showPicker: true

  # generate social links in footer
  social_links:
    twitter: dustinhennis
    github:  dustinhennis
    linkedIn: in/dustinhennis
    # rss: rss
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed