title: GitHub Pages (dustinhennis)
author:
  name: Dustin Hennis
  email: dustin at linux dot com
description: > 
  My GitHub pages site for random posts and testing

show_excerpts: true

minima:
  date_format: "%b %-d, %Y"

  social_links:
    twitter: dustinhennis
    github:  dustinhennis
    linkedin: dustinhennis

header_pages:
 - about.md
 - tags.md

theme: minima
#remote_theme: "mmistakes/minimal-mistakes@4.24.0"

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-gist
